[theme]

# Primary accent for interactive elements
primaryColor = '#869F77'

# Background color for the main content area
backgroundColor = '#FFDDD6'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F1B6AC'

# Color used for almost all text
textColor = '#c10016'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"